import type { NextPage } from "next";
import Head from "next/head";
import Footer from "../components/commons/Footer";
import Header from "../components/commons/Header";
import Layout from "../components/commons/Layout";
import Main from "../components/commons/Main";
import SectionTitle from "../components/commons/SectionTitle";
import CTA from "../components/CTA";
import Hero from "../components/Hero";
import Latest from "../components/Latest";
import SectionHomeList from "../components/SectionHomeList";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Encontre seu Seminovo na Ponto 7 Veículos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Header />
        <Hero />
        <Main>
          <Latest />
          <CTA />
          <SectionTitle>
            <h1 className="title-font text-3xl font-medium uppercase text-gray-900 mt-6 mb-5">
              Seminovos
            </h1>
          </SectionTitle>
          <SectionHomeList />
        </Main>
        <Footer />
      </Layout>
    </div>
  );
};

export default Home;
