import { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { Cars } from "../types";
import { fetchAPI } from "../services/api";
import Layout from "../components/commons/Layout";
import Main from "../components/commons/Main";
import SectionTitle from "../components/commons/SectionTitle";
import CTA from "../components/CTA";
import Hero from "../components/Hero";
import Latest from "../components/Latest";
import SectionHomeList from "../components/SectionHomeList";
import { ReactElement } from "react";

const Home = ({ cars }: Cars): ReactElement => {
  return (
    <>
      <Head>
        <title>Encontre seu Seminovo na Ponto 7 Veículos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Hero />
        <Main>
          <Latest />
          <CTA />
          <SectionTitle>
            <h1 className="title-font text-3xl font-medium uppercase text-gray-900 mt-6 mb-5">
              Seminovos
            </h1>
          </SectionTitle>
          <SectionHomeList />
        </Main>
      </Layout>
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  // Run API calls in parallel
  const cars: Cars[] = await fetchAPI("/cars");

  return {
    props: { cars },
    revalidate: 1,
  };
};

export default Home;
